---
baseurl: "https://martinliu.cn/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "Martin's Blog"
theme: "beautifulhugo"
metaDataFormat: "yaml"
subtitle: "I am a runner, blogger and huge fan of open source."
dateFormat: "2006, January 2"
description: "DevOps Coach | Community Advocate | Cloud Computing expert"
---

